// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace MatoRecipe_Model.Model
{

    public class FoodDetailEntity
    {

        [JsonProperty("count")]
        public int Count { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("disease")]
        public string Disease { get; set; }

        [JsonProperty("fcount")]
        public int Fcount { get; set; }

        [JsonProperty("food")]
        public string Food { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("img")]
        public string Img { get; set; }

        [JsonProperty("keywords")]
        public string Keywords { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("rcount")]
        public int Rcount { get; set; }

        [JsonProperty("status")]
        public bool Status { get; set; }

        [JsonProperty("summary")]
        public string Summary { get; set; }

        [JsonProperty("symptom")]
        public string Symptom { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }
    }

}
