//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace MatoRecipe_Model.Model
{
    /// <summary>
    /// 实体类cook_2_food。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("cook_2_food")]
    [Serializable]
    public partial class cook_2_food : Entity
    {
        #region Model
		private int _Id;
		private int _cook_id;
		private int _food_id;
		private DateTime _create_time;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("cook_id")]
		public int cook_id
		{
			get{ return _cook_id; }
			set
			{
				this.OnPropertyValueChange("cook_id");
				this._cook_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("food_id")]
		public int food_id
		{
			get{ return _food_id; }
			set
			{
				this.OnPropertyValueChange("food_id");
				this._food_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("create_time")]
		public DateTime create_time
		{
			get{ return _create_time; }
			set
			{
				this.OnPropertyValueChange("create_time");
				this._create_time = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.cook_id,
				_.food_id,
				_.create_time,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._cook_id,
				this._food_id,
				this._create_time,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "cook_2_food");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "cook_2_food", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field cook_id = new Field("cook_id", "cook_2_food", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field food_id = new Field("food_id", "cook_2_food", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field create_time = new Field("create_time", "cook_2_food", "");
        }
        #endregion
	}
}