//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace MatoRecipe_Model.Model
{
    /// <summary>
    /// 实体类cook_show_item。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("cook_show_item")]
    [Serializable]
    public partial class cook_show_item : Entity
    {
        #region Model
		private int _Id;
		private int _classify_id;
		private int? _count;
		private string _description;
		private int? _fcount;
		private string _food;
		private string _img;
		private string _name;
		private int? _rcount;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("classify_id")]
		public int classify_id
		{
			get{ return _classify_id; }
			set
			{
				this.OnPropertyValueChange("classify_id");
				this._classify_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("count")]
		public int? count
		{
			get{ return _count; }
			set
			{
				this.OnPropertyValueChange("count");
				this._count = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("description")]
		public string description
		{
			get{ return _description; }
			set
			{
				this.OnPropertyValueChange("description");
				this._description = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("fcount")]
		public int? fcount
		{
			get{ return _fcount; }
			set
			{
				this.OnPropertyValueChange("fcount");
				this._fcount = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("food")]
		public string food
		{
			get{ return _food; }
			set
			{
				this.OnPropertyValueChange("food");
				this._food = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("img")]
		public string img
		{
			get{ return _img; }
			set
			{
				this.OnPropertyValueChange("img");
				this._img = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("name")]
		public string name
		{
			get{ return _name; }
			set
			{
				this.OnPropertyValueChange("name");
				this._name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("rcount")]
		public int? rcount
		{
			get{ return _rcount; }
			set
			{
				this.OnPropertyValueChange("rcount");
				this._rcount = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.classify_id,
				_.count,
				_.description,
				_.fcount,
				_.food,
				_.img,
				_.name,
				_.rcount,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._classify_id,
				this._count,
				this._description,
				this._fcount,
				this._food,
				this._img,
				this._name,
				this._rcount,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "cook_show_item");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "cook_show_item", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field classify_id = new Field("classify_id", "cook_show_item", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field count = new Field("count", "cook_show_item", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field description = new Field("description", "cook_show_item", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field fcount = new Field("fcount", "cook_show_item", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field food = new Field("food", "cook_show_item", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field img = new Field("img", "cook_show_item", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field name = new Field("name", "cook_show_item", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field rcount = new Field("rcount", "cook_show_item", "");
        }
        #endregion
	}
}