//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace MatoRecipe_Model.Model
{
    /// <summary>
    /// 实体类show_item_classify。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("show_item_classify")]
    [Serializable]
    public partial class show_item_classify : Entity
    {
        #region Model
		private int _Id;
		private int _classify_id;
		private int _item_id;
		private DateTime _create_time;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("classify_id")]
		public int classify_id
		{
			get{ return _classify_id; }
			set
			{
				this.OnPropertyValueChange("classify_id");
				this._classify_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("item_id")]
		public int item_id
		{
			get{ return _item_id; }
			set
			{
				this.OnPropertyValueChange("item_id");
				this._item_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("create_time")]
		public DateTime create_time
		{
			get{ return _create_time; }
			set
			{
				this.OnPropertyValueChange("create_time");
				this._create_time = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.classify_id,
				_.item_id,
				_.create_time,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._classify_id,
				this._item_id,
				this._create_time,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "show_item_classify");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "show_item_classify", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field classify_id = new Field("classify_id", "show_item_classify", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field item_id = new Field("item_id", "show_item_classify", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field create_time = new Field("create_time", "show_item_classify", "");
        }
        #endregion
	}
}